language: perl
sudo: false

addons:
  apt:
    packages:
      - libarchive-dev

install:
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

  - cpanm Devel::CheckLib AnyEvent::Open3::Simple HTTP::Tiny
  - cpanm FFI::Raw -n || true
  - cpanm Alien::patch

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - dzil test -v

